name: mflix_app
description: A Flutter app to display movie information.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.5
  http: ^1.5.0
  cached_network_image: ^3.3.0
  ditto_live: ^5.0.3
  ditto_flutter_tools: ^3.0.0-rc.2
  permission_handler: ^11.3.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default.png
